name: my_fave_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.6
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  firebase_auth: ^4.15.3
  firebase_core: ^2.23.0
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_config: ^2.0.2
  flutter_hooks: ^0.20.3

  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.4.6
  image: ^4.1.3
  image_cropper: ^5.0.1
  image_picker: ^1.0.5
  intl: ^0.18.1
  json_annotation: ^4.8.1
  material_color_utilities: ^0.5.0
  riverpod_annotation: ^2.3.3
  table_calendar: ^3.0.9
  uuid: ^4.2.2


dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.4
  json_serializable: ^6.7.1
  pedantic_mono: any
  riverpod_generator: ^2.3.9


flutter:
  uses-material-design: true

  assets:
      - assets/icons/
      - assets/images/

flutter_gen:
  output: lib/utils/gen/