name: my_fave_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.6
  intl: ^0.18.1
  json_annotation: ^4.8.1


dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  pedantic_mono: any


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  output: lib/utils/gen/